// Autogenerated CHmUsiCK file from CQenze

Gain gate => dac;

Sampler d2 => gate;
Sampler d3 => gate;
Sampler d4 => gate;

d2.file("sn","");
d3.file("cp","");
d4.file("bd","");

spork~d2.soundT([0,1]);
spork~d3.soundC([0,1]);
spork~d4.soundT([1,1]);

2::second => now;
