#!/usr/bin/env python

from subprocess import call
import time, os

while(True):
    try:
        #size = os.path.getsize("Live.cqz")
        time.sleep(0.2)
        #if size >= 1:
        call(["./src/translate","Live.cqz"])
        #    with open("Live.cqz","w") as live:
        #        live.write("")
    except (KeyboardInterrupt, SystemExit):
        print "\nleaving CQenze..\n"
        quit()
 
